#!/usr/bin/python
# Copyright Tal Wrii

"Prompt for new window using dmenu (completion), create a new window if we cannot find window ala emacs."

import subprocess

def display(msg):
    return subprocess.call(['tmux', 'display-message', msg])

def dmenu_prompt(prompt, choices):
    p = subprocess.Popen(
        ['dmenu', '-p', prompt], 
        stdout=subprocess.PIPE, stdin=subprocess.PIPE)
    choice_string = '\n'.join(choices)
    reply, _ = p.communicate(choice_string)
    return reply.strip()


display('Switching using dmenu')
windows_string = subprocess.check_output(
    ['tmux', 'list-windows', '-F', '#{window_name}'])
windows = windows_string.splitlines()

chosen_window = dmenu_prompt('Switch to tmux-window', windows)

if chosen_window == '':
    display("Cancelled")
elif chosen_window not in windows:
    prompt = 'Create new window: {}?'.format(chosen_window)
    response = dmenu_prompt(prompt, 'yn')
    if response == 'y':
        subprocess.call(['tmux', 'new-window', '-n', chosen_window]) 
    else:
        display("You chose to not create a new window")
else:
    subprocess.call(['tmux', 'select-window', '-t', chosen_window])
